version: "3"

services:
  mongodb:
    image: mongo
    container_name: mongodb-container
    ports:
      - 8094:27017
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=monjoy
      - MONGO_INITDB_ROOT_PASSWORD=monjoy
    networks:
      - my-network
  mongo-express:
    image: mongo-express
    container_name: mongo_express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=monjoy
      - ME_CONFIG_MONGODB_ADMINPASSWORD=monjoy
      - ME_CONFIG_MONGODB_SERVER=mongodb-container
    networks:
      - my-network
volumes:
  mongo: {}
networks:
  my-network:
    driver: bridge