version: "3.6"

services:
  # frontend:
  #   image: monjoychoudhury29/foodle-frontend:latest
  #   ports:
  #     - "3000:3000"
  #   pull_policy: always
  #   networks:
  #     - my-network
  #   container_name: frontend
  discovery-service:
    image: monjoychoudhury29/foodle-service-discovery:latest
    ports:
      - "8761:8761"
    container_name: discovery-service
    pull_policy: always
    networks:
      - my-network

  api-gateway:
    image: monjoychoudhury29/foodle-api-gateway:latest
    ports:
      - "9191:9191"
    depends_on:
      - discovery-service
    container_name: api-gateway
    pull_policy: always
    networks:
      - my-network

  canteen-service:
    image: monjoychoudhury29/foodle-canteen-service:latest
    ports:
      - "8084:8084"
    depends_on:
      - discovery-service
    container_name: canteen-service
    pull_policy: always
    networks:
      - my-network
    volumes:
      - ./logs:/var/log/canteen.log

  feedback-service:
    image: monjoychoudhury29/foodle-feedback-service:latest
    ports:
      - "8082:8082"
    depends_on:
      - discovery-service
    container_name: feedback-service
    pull_policy: always
    networks:
      - my-network

  mess-menu-service:
    image: monjoychoudhury29/foodle-mess-menu:latest
    ports:
      - "8085:8085"
    depends_on:
      - discovery-service
    pull_policy: always
    container_name: mess-menu-service
    networks:
      - my-network

  user-service:
    image: monjoychoudhury29/foodle-user-service:latest
    ports:
      - "8086:8086"
    depends_on:
      - discovery-service
    pull_policy: always
    container_name: user-service
    networks:
      - my-network

  service-request:
    image: monjoychoudhury29/foodle-service-request:latest
    ports:
      - "8083:8083"  
    depends_on:
      - discovery-service
    pull_policy: always
    container_name: service-request
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
