version: "3.6"

services:
  frontend:
    image: monjoychoudhury29/foodle-frontend:latest
    ports:
      - "3000:3000"
    pull_policy: always
    networks:
      - my-network
  discovery-service:
    image: monjoychoudhury29/foodle-service-discovery:latest
    ports:
      - "8761:8761"
    container_name: discovery-service
    pull_policy: always
    networks:
      - my-network

  api-gateway:
    image: monjoychoudhury29/foodle-api-gateway:latest
    ports:
      - "9191:9191"
    depends_on:
      - discovery-service
    pull_policy: always
    networks:
      - my-network

  canteen-service:
    image: monjoychoudhury29/foodle-canteen-service:latest
    ports:
      - "8084:8084"
    depends_on:
      - discovery-service
    pull_policy: always
    networks:
      - my-network

  feedback-service:
    image: monjoychoudhury29/foodle-feedback-service:latest
    ports:
      - "8082:8082"
    depends_on:
      - discovery-service
    pull_policy: always
    networks:
      - my-network

  mess-menu-service:
    image: monjoychoudhury29/foodle-mess-menu:latest
    ports:
      - "8085:8085"
    depends_on:
      - discovery-service
    pull_policy: always
    networks:
      - my-network

  user-service:
    image: monjoychoudhury29/foodle-user-service:latest
    ports:
      - "8086:8086"
    depends_on:
      - discovery-service
    pull_policy: always
    networks:
      - my-network

  service-request:
    image: monjoychoudhury29/foodle-service-request:latest
    ports:
      - "8083:8083"  
    depends_on:
      - discovery-service
    pull_policy: always
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
