services:
  mongodb:
    image: mongo
    container_name: mess-menu-db
    ports:
      - 8094:27017
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=monjoy
      - MONGO_INITDB_ROOT_PASSWORD=monjoy
  mongo-express:
    image: mongo-express
    container_name: mongo_express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=monjoy
      - ME_CONFIG_MONGODB_ADMINPASSWORD=monjoy
      - ME_CONFIG_MONGODB_SERVER=mongodb

volumes:
  mongo: {}