spring:
  application:
    name: SERVICE-REQUEST
  data:
    mongodb:
      username: monjoy
      password: monjoy
      host: localhost
      port: 8094
      database: service-request
      authentication-database: admin
server:
  port: 8083
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      # defaultZone: http://localhost:8761/eureka/
      defaultZone: http://discovery-service:8761/eureka/
  instance:
    hostname: localhost
logging.level.org.springframework.web: DEBUG
logging.level.com.eic.foodle.parser: DEBUG
