spring:
  application:
    name: user-service
  data:
    mongodb:
      username: monjoy
      password: monjoy
      host: localhost
      port: 8094
      database: users
      authentication-database: admin

server:
  port: 8086
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka