spring:
  application:
    name: MESS-MENU-SERVICE
  data:
    mongodb:
      username: monjoy
      password: monjoy
      host: localhost
      port: 8094
      database: mess-menu
      authentication-database: admin

server:
  port: 8085
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost