spring:
  application:
    name: CANTEEN-SERVICE
  data:
    mongodb:
      username: monjoy
      password: monjoy
      host: mongodb-container
      port: 27017
      database: canteen-menu
      authentication-database: admin

server:
  port: 8084

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
      # defaultZone: http://localhost:8761/eureka/
  instance:
    # hostname: localhost
    preferIpAddress: true

management:
  security:
    enabled: false

#logging:
#  level:
#    com.eic.canteenservice: DEBUG
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"
#    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"
#  appenders:
#    file:
#      file: /logs/peepee.log
#      maxFileSize: 10MB
#      backupIndex: 10
#

