spring:
  application:
    name: service-request
  data:
    mongodb:
      username: monjoy
      password: monjoy
      host: localhost
      port: 8094
      database: service-request
      authentication-database: admin
server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
