spring:
  application:
    name: FEEDBACK-SERVICE
  data:
    mongodb:
      username: monjoy
      password: monjoy
      host: mongodb-container
      port: 27017
      database: feedbacks
      authentication-database: admin
server:
  port: 8082
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      # defaultZone: http://localhost:8761/eureka/
      defaultZone: http://discovery-service:8761/eureka/
  instance:
    # hostname: localhost
    preferIpAddress: true
