spring:
  application:
    name: USER-SERVICE
  data:
    mongodb:
      username: monjoy
      password: monjoy
      host: localhost
      port: 8094
      database: users
      authentication-database: admin

server:
  port: 8086
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      # defaultZone: http://localhost:8761/eureka/
      defaultZone: http://discovery-service:8761/eureka/
  instance:
    hostname: localhost
