spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 11MB
  application:
    name: PARSER
  http:
    multipart:
      enable: true
      max-file-size: 10MB
      max-request-size: 11MB


server:
  port: 8089
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

logging.level.org.springframework.web: DEBUG
logging.level.com.eic.foodle.parser: DEBUG