spring:
  application:
    name: USER-SERVICE
  data:
    mongodb:
      uri: mongodb://monjoy:monjoy@localhost:8094/?authMechanism=DEFAULT&authSource=admin
      username: monjoy
      password: monjoy
      host: mongodb
      port: 8094
      database: users
      authentication-database: admin

server:
  port: 8086
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      # defaultZone: http://localhost:8761/eureka/
      defaultZone: http://discovery-service:8761/eureka/
  instance:
    # hostname: localhost
    preferIpAddress: true
