name: Build and Publish - API Gateway

on:
  push:
    branches:
      - api-gateway

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v4.0.0
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t monjoychoudhury29/foodle-api-gateway:latest .
          docker push monjoychoudhury29/foodle-api-gateway:latest

        env:
          DOCKER_BUILDKIT: 1
          DOCKER_CLI_ACI: 1
